-- ===============================================================
-- 01_grant_dbt_role.sql
-- Purpose: Grant privileges to DBT_ROLE for RAW and SILVER layers
-- ===============================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE DBT_DB;

-- Grant access to RAW schema
GRANT USAGE ON SCHEMA DBT_DB.RAW TO ROLE DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DB.RAW TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DB.RAW TO ROLE DBT_ROLE;
GRANT REFERENCES ON ALL TABLES IN SCHEMA DBT_DB.RAW TO ROLE DBT_ROLE;

-- Grant access to SILVER schema
GRANT USAGE ON SCHEMA DBT_DB.SILVER TO ROLE DBT_ROLE;
GRANT CREATE VIEW ON SCHEMA DBT_DB.SILVER TO ROLE DBT_ROLE;
GRANT CREATE TABLE ON SCHEMA DBT_DB.SILVER TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA DBT_DB.SILVER TO ROLE DBT_ROLE;

-- Grant access to GOLD schema for downstream model references
GRANT USAGE ON SCHEMA DBT_DB.GOLD TO ROLE DBT_ROLE;
GRANT CREATE TABLE ON SCHEMA DBT_DB.GOLD TO ROLE DBT_ROLE;
GRANT CREATE VIEW ON SCHEMA DBT_DB.GOLD TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA DBT_DB.GOLD TO ROLE DBT_ROLE;

